server:
  port: 4040

spring:
  application:
    name: Ticketing System
  datasource:
    url: jdbc:postgresql://postgres:5432/ticketing_db
    username: atacanyavuz
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.atacanyavuz.ticketing: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log